remote_theme: cotes2020/jekyll-theme-chirpy
title: Beer Ratings Directory
description: My ratings from ratebeer
timezone: UTC
lang: en
author:
  name: Your Name
  email: your-email@example.com
url: "https://gareth-rl.github.io"
baseurl: "/beer"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
header:
  logo:
    text: Beer Ratings
    url: /
sass:
  load_paths:
    - _sass/custom
